export const PAIR_LIST = 'PAIR_LIST';

export const SPOT_TRADE_PAIR = 'SPOT_TRADE_PAIR';

export const SET_SPOT_MARKET_PRICE = 'SET_SPOT_MARKET_PRICE'

export const SET_ASSET_DATA = 'SET_ASSET_DATA'

export const CURRENCY_LIST = 'CURRENCY_LIST'

export const LAUNCH_CREATEDATA = 'LAUNCH_CREATEDATA'

export const APPROVE_TOKEN = "APPROVE_TOKEN"

export const MARGIN_LIST = 'MARGIN_LIST'//For margin pair list

export const MARGIN_TRADE_PAIR = 'MARGIN_TRADE_PAIR';

export const SET_MARGIN_MARKET_PRICE = 'SET_MARGIN_MARKET_PRICE'


export const DERIVATIVE_LIST = 'DERIVATIVE_LIST'//For DERIVATIVE pair list


export const DERIVATIVE_TRADE_PAIR = 'DERIVATIVE_TRADE_PAIR'

export const SET_DERIVATIVE_MARKET_PRICE = 'SET_DERIVATIVE_MARKET_PRICE'

export const FUTURES_TRADE_PAIR = 'FUTURES_TRADE_PAIR'

export const SET_FUTURES_MARKET_PRICE = 'SET_FUTURES_MARKET_PRICE'


export const PRICE_CONVERSION_LIST = 'PRICE_CONVERSION_LIST'

export const SPOT_ORDERBOOK_PRICE = 'SPOT_ORDERBOOK_PRICE'
export const MARGIN_ORDERBOOK_PRICE = 'MARGIN_ORDERBOOK_PRICE'

export const CONNECTION_STATE = 'CONNECTION_STATE'


/** copy-trade */
export const ALL_STRATEGY = 'ALL_STRATEGY'
export const MY_STRATEGY = 'MY_STRATEGY'
